{
 "title": "Simulator",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Latest",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "group_d_latest{}", "legendFormat": "Latest" }
   ]
  },
  {
   "title": "Tweet",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "expr": "group_d_tweet{}", "legendFormat": "Tweet" }
   ]
  },
  {
   "title": "Unfollow",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "group_d_unfollow{}", "legendFormat": "Unfollow" }
   ]
  },
  {
   "title": "Follow",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    { "expr": "group_d_follow{}", "legendFormat": "Follow" }
   ]
  },
  {
   "title": "ReadTimeout",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    { "expr": "group_d_read_timeout{}", "legendFormat": "ReadTimeout" }
   ]
  },
  {
   "title": "ConnectionError",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    { "expr": "group_d_connection_error{}", "legendFormat": "ConnectionError" }
   ]
  },
  {
   "title": "Register",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    { "expr": "group_d_register{}", "legendFormat": "Register" }
   ]
  },
  {
   "title": "Increase in errors",
   "type": "gauge",
   "description": "All lines should be zero. Then the Simulator doesn't see any errors.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(group_d_register{}[$__range])",
     "legendFormat": "Register"
    },
    {
     "expr": "rate(group_d_follow{}[$__range])",
     "legendFormat": "follow"
    },
    {
     "expr": "rate(group_d_unfollow{}[$__range])",
     "legendFormat": "Unfollow"
    },
    {
     "expr": "rate(group_d_tweet{}[$__range])",
     "legendFormat": "Tweet"
    },
    {
     "expr": "rate(group_d_connection_error{}[$__range])",
     "legendFormat": "ConnectionError"
    },
    {
     "expr": "rate(group_d_read_timeout{}[$__range])",
     "legendFormat": "ReadTimeout"
    }
   ]
  },
  {
   "title": "Increase in errors",
   "type": "timeseries",
   "description": "All lines should be zero. Then the Simulator doesn't see any errors.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "rate(group_d_register{}[$__range])",
     "legendFormat": "Register"
    },
    {
     "expr": "rate(group_d_follow{}[$__range])",
     "legendFormat": "follow"
    },
    {
     "expr": "rate(group_d_unfollow{}[$__range])",
     "legendFormat": "Unfollow"
    },
    {
     "expr": "rate(group_d_tweet{}[$__range])",
     "legendFormat": "Tweet"
    },
    {
     "expr": "rate(group_d_connection_error{}[$__range])",
     "legendFormat": "ConnectionError"
    },
    {
     "expr": "rate(group_d_read_timeout{}[$__range])",
     "legendFormat": "ReadTimeout"
    }
   ]
  }
 ]
}